FROM jc21/rpmbuild-centos8:latest

LABEL maintainer="Jamie Curnow <jc@jc21.com>"

USER root

# Golang
RUN yum -y update \
	&& yum -y install golang \
	&& yum clean all \
	&& rm -rf /var/cache/yum

# Update golang
RUN yum localinstall -y \
	https://yum.jc21.com/centos/base/el/all/noarch/golang-docs-1.19.4-1.noarch.rpm \
	https://yum.jc21.com/centos/base/el/all/noarch/golang-misc-1.19.4-1.noarch.rpm \
	https://yum.jc21.com/centos/base/el/all/noarch/golang-src-1.19.4-1.noarch.rpm \
	https://yum.jc21.com/centos/base/el/all/noarch/golang-tests-1.19.4-1.noarch.rpm \
	https://yum.jc21.com/centos/base/el/all/x86_64/golang-1.19.4-1.x86_64.rpm \
	https://yum.jc21.com/centos/base/el/all/x86_64/golang-bin-1.19.4-1.x86_64.rpm \
	https://yum.jc21.com/centos/base/el/all/x86_64/golang-race-1.19.4-1.x86_64.rpm \
	https://yum.jc21.com/centos/base/el/all/x86_64/golang-shared-1.19.4-1.x86_64.rpm

USER rpmbuilder

